### ISSUE TITLE
User Can't Login

### ISSUE THREAD

**Issue by mo-kalaleeb** [yes-soft-de/delivery-skeleton#4]
Issue: 
Can't create a user.

Branch:
master
dev-backend

Endpoint:
http://localhost:443/user

Method:
Post

Request:
{
    "userID": "123",
    "password": "123456a@"
}

Response:
Attempted to call an undefined method named "setPassword" of class "App\Entity\StoreOwnerProfileEntity".

![image](https://user-images.githubusercontent.com/50542912/118777701-06938800-b892-11eb-85fc-13a152d1d725.png)

**Comment by mo-kalaleeb** [comment]
@Kenan-Hussein

**Comment by habibdevsy** [comment]
In the next release, this route has been removed and there is no problem with a new user create.
  please waiting next push ^_^

**Comment by Kenan-Hussein** [comment]
@MickSawy3r 
please use dev -backend branch
